import math
import SmithWaterman as sm

#jukesCantor: implementation of the JukesCantor Distance Alg
#params: s1 (aligned nucleotide sequence), s2 (aligned nucleotide sequence)
#output: numeric value representing evolutionary distance
def jukesCantor(s1, s2):
    diffCtr = 0;
    lenCtr = 0;

    for i in range (len(s1)):
        if ((s1[i] != '-') and (s2[i] != '-')):
            lenCtr = lenCtr + 1
            if (s1[i] != s2[i]):
                diffCtr = diffCtr + 1
    print (diffCtr)
    diffCtr = float(diffCtr/lenCtr)
    print (lenCtr)
    print (diffCtr)

    jukes = (-3/4 * math.log(1-(4/3 * diffCtr)))

    return jukes

def prettyPrint(s1, s2, width):
    curIndex = 0
    res = ""
    pretty = "seq1: {}  \t{}\t{}\nseq2: {}  \t{}\t{}\n"
    while len(s1) > 0:
        if len(s1) < width:
            width = len(s1)
        seg1 = s1[0:width]
        seg2 = s2[0:width]

        res += pretty.format(curIndex, seg1, curIndex+width-1,curIndex, seg2, curIndex+width-1)
        s1 = s1[curIndex:]
        s2 = s2[curIndex:]
        curIndex = curIndex + width;

    return res;


class distanceMatrix:
    #do stuff here to build the matrix
seq1 = "CCTCCGCCTTTAGGCGGTGCTTACTCTTTCATAAAGGGGCTGTTAGTTATGCCCCGCGAGGATTCGAAAAGGTGAGCCAACTCGGCCGATCCGGAGAGACGGGCTTCAAAGCTGCCTGACGACGGTTGTGGGCCCGTAACAAAATCCTCCCAATAAGCCCCCGTGAGCGTCGGTTGAACAGCCCTGGTCGGCCCGACCAGAAGCCCGAATATATCGCTTTACGGCTCTTGGGCCGGGGTGCGTTACCTTGCAGAAATCGAGGCCGTCCGTTAATTCCTGTTGCATTCATACCGCGTATATTTGTCTCTTTACCCGCTTACTTGGATAAGCATGGCATAGCTTTTTATCGGAGCGCCTCCGTACACGGTACGATCGCACGCCTCGTGAGATCAATACGTATACCAGGTGTCCTGTGAGCAGCGAAAGCCTAAACGGGAGATACACCGCCAAAAGTCCGTGTGAATACGAGTCGTGGCAAATTTGGTCTGGCTGTGATCTAGATATTCCAGGCGGTACGTCTGCTCTCGCGTGCCTCTAGTGGCTCGCTAGATAGTCTAGCCGCTGGTAAACACTCCATGACCCCGGCTCTCCATTGATGCCACGGCGATTGTTGGAGAGCCAGCAGCGACTGCAAACGTCAGATCAGAGTAATACTAGCAAGCGATAAGTCCCTAACTGGTTGTGGCCTTCTGTAGAGTGAACTTCACCACATATGCTGTCTCTGGCACGTGGATGGTTTGGAGAAATCAGATTCAAGTCTGATCAACCTTCAAACAGATCTAGAGTCTAAAACAGTGATCTCCTGCGTGCGAGATAGAAATACTAGGTAACTACAGGGACTGCGACGTTTTAAACGTTGGTCCGTCAGAAGCGCCATTCAGGATCACGTTACCCCGAAAAAAAGGTACCAGGAGCTCTTCTCCTCTGCAGTCAGGTCTATAGAAACTACACCATTAACCTTCCTGAGAACCGGGAGGTGGGAATCCGTCACATATGAGAA"
seq2 = "GGTATTTGCCCGATAATCAATACTCCAGGCTTCTAACTTTTTCCACTCGCTTGAGCCGGCTTGGCCTTTCTGCCTGAAGATTCGTTGGACTGGTGCCAACGCGCAGGCATAGTTCCAGGAGAATTATCCGGGGGCAGTGACAACCAACATCTCGGGTCTTGCCCAACCGGTCTACACGCTGATATAGCGAATCACCGAGAACCCGGCGCCACGCAATGGAACGTCCTTAACTCTGGCAGGCAATTAAAGGGAACGTATATATAACGCAAAAAAACTGGAAAATTGGCGAGAGAATCTTCTCTCTGTCTATCGAAGAATGGCCACGCGGAGGCATGCGTCATGCTAGCGTGCGGGGTACTCTTGCTATCCATTTGGGTCACAGGACACTCGCTGTTTTCGAATTTACCCTTTATGCGCCGGTATTGAACCACGCTTATGCCCAGCATCGTTACAACCAGACTGATACTAGATGTATAATGTCCGCCATGCAGACGAAACCAGTCGGAGATTACCGAGCATTCTATCACGTCGGCGACCACTAGTGAGCTACTGGAGCCGAGGGGTAACGATGATGCCCCTAAGAACCTCTCGGTCGACGCAAGCGATTACACTCCTGTCACATCATAATCGTTTGCTATTCAGGGGTTGACCAACACCGGATAGCTTTTCACTTGAAGTATTATGCACGACAGGGTGCGTGTACCAACTAAACCTGTTTTAACTTACCTCAGACTAGTTGGAAGTGTGGCTAGATCTTAGCTTTCGTCACTAGAGGGCCCACGCTTAGTTTTTATGATCCATTGATCTCCTAGACGCTGCAAGATTTGCAACCAGGCAGACTTAGCGGTAGGTCCTAGTGCAGCGGGACTTTTTTTCTATAGTCGTTGAGAGGAGGAGTCGTCAGACCAGATACCTTTGATGTCCTGATTGGAAGGACCGTTGGCCCCCGACCCTTAGACAGTGTACTCAGTTCTATAAACGAGCTATTAG"
sm.seq1 = seq1
sm.seq2 = seq2

match = 2
mismatch = -1

rows = (len(seq1) +1)
cols = (len(seq2) +1)

score_matrix, start_pos = sm.create_score_matrix(rows, cols)

seq1_aligned, seq2_aligned = sm.traceback(score_matrix, start_pos)

print (prettyPrint(seq1_aligned, seq2_aligned,100))
print ('jukesCantor distance: {}'.format(jukesCantor(seq1_aligned,seq2_aligned)))
